In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('인하대역 이용승객 데이터.csv') 
#csv 파일의 경로를 지정해주거나, 이렇게 지정 후 이 ipynb파일과 동일 폴더에 저장해두면 됨

data.iloc[0:24]

    이용시간  월요일  화요일  수요일  목요일  금요일
0    900  256  241  250  227  226
1    930  196  198  228  200  205
2   1000  161  165  202  156  183
3   1030  219  221  183  193  184
4   1100  164  149  192  134  185
5   1130  161  180  157  146  148
6   1200  167  162  165  168  200
7   1230  179  209  172  180  182
8   1300  180  173  199  174  240
9   1330  195  179  200  199  176
10  1400  161  175  185  161  195
11  1430  174  209  193  175  172
12  1500  198  175  182  143  203
13  1530  211  182  205  207  186
14  1600  209  244  229  236  253
15  1630  279  285  259  278  296
16  1700  314  297  332  309  355
17  1730  414  428  380  400  386
18  1800  471  437  490  448  513
19  1830  360  367  347  360  356
20  1900  250  225  250  201  258
21  1930  225  227  220  195  200
22  2000  175  194  209  233  194
23  2030  188  180  196  205  200

In [3]:
week = ['월', '화', '수', '목', '금']
day = input("무슨 요일인가요? : ")
while not day in week or day in data:
        day = input("요일을 제대로 입력해주세요 : ")
        if day in week or day in data:
            break
if day in week:
    day = day + '요일'

ending_time = int(input("수업 종료 시간(ex:1200) : "))
arrive_time = int(input("도착해야하는 시간(ex:1600) : "))
while ending_time > arrive_time:
    print("진심이면 외박밖에 답이 없습니다.")
    arrive_time = int(input("도착해야하는 시간을 제대로 입력해주세요 : "))
spending_time = int(input("소요되는 시간(ex:230 - 2시간 30분) : "))

무슨 요일인가요? : 토
요일을 제대로 입력해주세요 : 일
요일을 제대로 입력해주세요 : ㅇ
요일을 제대로 입력해주세요 : 금요
요일을 제대로 입력해주세요 : 금
수업 종료 시간(ex:1200) : 1500
도착해야하는 시간(ex:1600) : 1200
진심이면 외박밖에 답이 없습니다.
도착해야하는 시간을 제대로 입력해주세요 : 1300
진심이면 외박밖에 답이 없습니다.
도착해야하는 시간을 제대로 입력해주세요 : 2300
소요되는 시간(ex:230 - 2시간 30분) : 100

In [4]:
data['afterschool'] = data['이용시간'] >= ending_time #수업시간 이후
data['available'] = (arrive_time - spending_time) >= data['이용시간'] #최대 탑승 가능 시간 (도착시간-소요시간)
indexlist = []
for i in data.index: #i를 index만큼 반복
    if str(data['afterschool'][i]) == 'True': #수업시간 이후이면서
        if str(data['available'][i]) == 'True': #탑승이 가능한 열차
            indexlist.append(i) #i를 리스트에 추가
            
min_value = data[day][indexlist[0]:indexlist[-1]].min() #리스트 범위 내에서 최소값 서치

min_index = data.index[data[day]==min_value] #그 최소값의 인덱스 서치

print(min_value, min_index) #참고용. 최소값과 인덱스 프린트

186 Int64Index([13], dtype='int64')

In [5]:
recommend = str(data['이용시간'].iloc[min_index].values) #추천 시간 (최소값에 대한 이용시간 데이터 프린트)
print(recommend)

[1530]

In [6]:
print('앉아서 가고 싶나? {0}:{1}에 열차를 타라.' .format(recommend[1:3], recommend[3:5]))

앉아서 가고 싶나? 15:30에 열차를 타라.